version: '3.8'

services:
  db:
    image: postgres:15
    container_name: multilingual-feedback-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d feedback_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  backend:
    build: ./backend
    container_name: multilingual-feedback-backend
    volumes:
      - ./backend:/code
    ports:
      - "8000:80"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./backend/.env
    command: >
      sh -c "sleep 5 && uvicorn app.main:app --host 0.0.0.0 --port 80 --reload"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: multilingual-feedback-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  adminer:
    image: adminer
    container_name: multilingual-feedback-adminer
    ports:
      - "8080:8080"

volumes:
  postgres_data:
